name: rko
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  just_audio: ^0.9.37
  lottie: ^3.1.0
  url_launcher: ^6.2.6

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/
    - assets/animations/

  fonts:
    - family: RkoIcons
      fonts:
        - asset: assets/fonts/rko-icons.ttf
    - family: Bahnschrift
      fonts:
        - asset: assets/fonts/bahnschrift.ttf
